name: Lint and Test

on:
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: true
      run_lint:
        required: false
        type: boolean
        default: true

jobs:
  lint:
    name: Verificar Lint
    if: ${{ inputs.run_lint == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar PMD
        working-directory: tp1
        run: mvn pmd:pmd

  test:
    name: Executar testes automatizados
    if: ${{ inputs.run_tests == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes
        working-directory: tp1
        run: mvn test