name: Criar Issue se condição falhar

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
jobs:
  verificar-e-criar-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Variável STAGE
        id: verificar
        run: |
          if [ -z "${{ vars.STAGE }}" ]; then
            echo "STAGE ausente!"
            echo "erro=true" >> $GITHUB_OUTPUT
          else
            echo "STAGE presente: ${{ vars.STAGE }}"
            echo "erro=false" >> $GITHUB_OUTPUT
          fi

      - name: Criar issue se STAGE estiver ausente
        if: steps.verificar.outputs.erro == 'true'
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Erro de Deploy: Variável STAGE ausente",
              "body": "A variável STAGE não está definida. Por favor, verifique a configuração do ambiente.",
              "labels": ["bug", "CI"]
            }'