name: Lint and Test

on:
  workflow_call:

jobs:
  lint:
    name: Verificar lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar PMD
        working-directory: tp1
        run: mvn pmd:pmd

  test:
    name: Executar testes automatizados
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes
        working-directory: tp1
        run: mvn test